### ISSUE TITLE
Utilizing cloud_exposure_types parameter in Expanse Task causes exception

### ISSUE THREAD

**Issue by andrew-expanse** [KennaPublicSamples/toolkit#39]
Hello,

When I attempt to use the `cloud_exposure_types` parameter with expanse I am seeing an exception coming from the mapper. 

Here's an example command which includes the `cloud_exposure_types` param with a list of different cloud exposure types.
```
docker pull quay.io/kennasecurity/toolkit && docker run -it -v /Users/andrew.scott/Dev/WIP/Kenna:/opt/app/toolkit/output quay.io/kennasecurity/toolkit task=expanse:kenna_api_key=$KENNA_API_KEY:expanse_api_key=$EXPANSE_API_KEY:cloud_exposure_types:insecure-signature-certificate-advertisements,internal-ip-address-advertisements,web-servers,expired-when-scanned-certificate-advertisements,application-server-software,self-signed-certificate-advertisements,EMBEDDED_SYSTEM,DATA_STORAGE_AND_ANALYSIS,short-key-certificate-advertisements,healthy-certificate-advertisements,NETWORKING_AND_SECURITY_INFRASTRUCTURE,unencrypted-logins,sharepoint-servers,BUILDING_CONTROL_SYSTEM,server-software,long-expiration-certificate-advertisements,development-environments,rdp-servers,JENKINS_SERVER,load-balancers,VPN,pop3-servers,wildcard-certificate-advertisements,domain-control-validated-certificate-advertisements,ftps-servers
```

The Exception I'm seeing is
```
Traceback (most recent call last):
2: from toolkit.rb:48:in `<main>'
1: from /opt/app/toolkit/tasks/expanse/expanse.rb:113:in `run'
/opt/app/toolkit/tasks/expanse/lib/mapper.rb:135:in `create_kdi_from_cloud_exposures': undefined method `sort' for "cloud_exposure_types":String (NoMethodError)
```

It seems like the mapper may be expecting that `cloud_exposure_types` is an array, but I believe it is still a string at this point. I think we may just need to add a `.split(',')` to the code in the mapper.

Let me know if you have any questions. Thanks!

**Comment by sfgeorge** [comment]
@andrew-expanse Thank you for that fantastic bug report!  I think you are spot-on there.  Could you attempt the fix (added to #40) and let us know if this solves the issue?  If, so we'll merge the change.

Thanks again for the great info and the help!
