### ISSUE TITLE
Expanse task error

### ISSUE THREAD

**Issue by Jeff-Lenton** [KennaPublicSamples/toolkit#55]
When running Expanse task. 

Traceback (most recent call last):
	6: from toolkit.rb:48:in `<main>'
	5: from /opt/app/toolkit/tasks/expanse/expanse.rb:105:in `run'
	4: from /opt/app/toolkit/tasks/expanse/lib/mapper.rb:81:in `create_kdi_from_exposures'
	3: from /opt/app/toolkit/tasks/expanse/lib/mapper.rb:81:in `each'
	2: from /opt/app/toolkit/tasks/expanse/lib/mapper.rb:87:in `block in create_kdi_from_exposures'
	1: from /opt/app/toolkit/lib/kdi/kdi_helpers.rb:60:in `create_kdi_asset'
/opt/app/toolkit/lib/kdi/kdi_helpers.rb:60:in `to_h': wrong element type Hash at 0 (expected array) (TypeError)

**Comment by sfgeorge** [comment]
@Jeff-Lenton Thank you so much for catching and reporting this!

We believe we've fixed this in #57.  Please pull the latest image (see [Running the latest image](https://github.com/KennaPublicSamples/toolkit#running-the-latest-image) if needed) and let us know whether or not this is resolved.

Thanks again for the detailed report!

**Comment by lindambrown** [comment]
fixed by check in yesterday

**Comment by Jeff-Lenton** [comment]
Now getting on latest

Traceback (most recent call last):
	9: from toolkit.rb:48:in `<main>'
	8: from /opt/app/toolkit/tasks/expanse/expanse.rb:124:in `run'
	7: from /opt/app/toolkit/lib/helpers.rb:82:in `write_file'
	6: from /usr/share/ruby/fileutils.rb:200:in `mkdir_p'
	5: from /usr/share/ruby/fileutils.rb:200:in `each'
	4: from /usr/share/ruby/fileutils.rb:215:in `block in mkdir_p'
	3: from /usr/share/ruby/fileutils.rb:215:in `reverse_each'
	2: from /usr/share/ruby/fileutils.rb:217:in `block (2 levels) in mkdir_p'
	1: from /usr/share/ruby/fileutils.rb:239:in `fu_mkdir'
/usr/share/ruby/fileutils.rb:239:in `mkdir': Permission denied @ dir_s_mkdir - /opt/app/toolkit/output/expanse (Errno::EACCES)

**Comment by Jeff-Lenton** [comment]
Confirmed fixed. Thanks!

**Comment by sfgeorge** [comment]
Thank you so much for reporting, @Jeff-Lenton!
